version: '3.5'  

services: 
  backend: 
    image: backend
    ports: 
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=example
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on:
      - db
      - redis
      - frontend
    restart: unless-stopped
  frontend:
    image: frontend
    ports: 
      - 5000:5000
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80