version: '3.5'  

services: 
  backend: 
    image: backend
    ports: 
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
  frontend:
    image: frontend
    ports: 
      - 5000:5000
  redis:
    image: "redis:alpine"
  
