version: '3.5'  

services:
  frontend:
    build:
      context:  ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  backend:
    build:
      context:  ./ml-kurkkumopo-backend
    volumes:
      - model:/src/model
    ports:
      - 5000:5000
  training:
    build:
      context:  ./ml-kurkkumopo-training  
    volumes:
      - model:/src/model
      - images:/src/imgs
      - data:/src/data  
volumes:
  model:
  images:
  data: